import random


def guess(a, b):
    random_number = random.randint(a, b)
    _guess = int(input('Enter the guess number: '))
    while _guess != random_number:
        if _guess > random_number:
            _guess = int(input('Too high bro. Try again: '))
            print('-'*20)
        elif _guess < random_number:
            _guess = int(input('Too small. Try again: '))
            print('-' * 20)
    print(f'Graz!!! Yoy have guessed the number {random_number}')
    print('''
                      .-.
         heehee      /aa \_
                   __\-  / )                 .-.
         .-.      (__/    /        haha    _/oo \ 
       _/ ..\       /     \               ( \ v /__
      ( \  u/__    /       \__             \/   ___)
       \    \__)   \_.-._._   )  .-.       /     \ 
       /     \             `-`  / ee\_    /       \_
    __/       \               __\  o/ )   \_.-.__   )
   (   _._.-._/     hoho     (___   \/           '-'
jgs '-'                        /     \ 
                             _/       \    teehee
                            (   __.-._/
                            ''')


if __name__ == '__main__':
    '''High it is guessing number game, where you can try
     to guess the number generated by your pc. Of course it will play with you
     "hot-cold" while you trying to guess it'''
    print("="*10 + "GUESSING GAME" + "="*10)
    max_x = int(input('Enter the upper limit for secret number: '))
    min_x = int(input('Enter the lower limit for secret number: '))
    if max_x < min_x:
        while max_x < min_x:
            print(f'upper limit: {max_x} is lower, than lower limit {min_x}\n'
                  f'try to enter the limits again\n' +
                  "*" * 20)
            max_x = int(input('Enter the upper limit for secret number: '))
            min_x = int(input('Enter the lower limit for secret number: '))
    guess(min_x, max_x)
